import { Column, Relationship, SchemaModel, Table } from '../types/schema';
import { normalizeType } from './typeSystem';

export function generatePostgres(schema: SchemaModel): string {
  let output = `-- PostgreSQL DDL Generated by RelationalCanvas\n-- Date: ${new Date().toISOString()}\n\n`;

  // Enable pgcrypto / uuid-ossp if uuid used
  const usesUUID = schema.tables.some(t => t.columns.some(c => c.type.toLowerCase().includes('uuid')));
  if (usesUUID) {
    output += `CREATE EXTENSION IF NOT EXISTS "pgcrypto";\n\n`;
  }

  for (const table of schema.tables) {
    output += `CREATE TABLE IF NOT EXISTS "${table.name}" (\n`;

    const lines: string[] = [];
    const pkColumns: string[] = [];

    for (const col of table.columns) {
      const type = normalizeType(col.type, 'postgres');
      let line = `  "${col.name}" ${type}`;

      if (col.isPrimaryKey) {
        pkColumns.push(`"${col.name}"`);
      }

      if (!col.isNullable && !col.isPrimaryKey) {
        line += ` NOT NULL`;
      }

      if (col.isUnique && !col.isPrimaryKey) {
        line += ` UNIQUE`;
      }

      if (col.defaultValue) {
        line += ` DEFAULT ${col.defaultValue}`;
      } else if (col.isPrimaryKey && type.toLowerCase() === 'uuid') {
        line += ` DEFAULT gen_random_uuid()`;
      }

      lines.push(line);
    }

    if (pkColumns.length > 0) {
      lines.push(`  CONSTRAINT "pk_${table.name}" PRIMARY KEY (${pkColumns.join(', ')})`);
    }

    // Table foreign keys
    const tableRels = schema.relationships.filter(r => r.sourceTableId === table.id);
    for (const rel of tableRels) {
      const srcCol = table.columns.find(c => c.id === rel.sourceColumnId);
      const tgtTable = schema.tables.find(t => t.id === rel.targetTableId);
      const tgtCol = tgtTable?.columns.find(c => c.id === rel.targetColumnId);

      if (srcCol && tgtTable && tgtCol) {
        lines.push(`  CONSTRAINT "fk_${table.name}_${srcCol.name}" FOREIGN KEY ("${srcCol.name}") REFERENCES "${tgtTable.name}" ("${tgtCol.name}") ON DELETE ${rel.onDelete || 'NO ACTION'}`);
      }
    }

    output += lines.join(',\n') + '\n);\n\n';

    // Explicit non-PK indexes
    const indexedCols = table.columns.filter(c => c.isIndexed && !c.isPrimaryKey && !c.isUnique);
    for (const col of indexedCols) {
      output += `CREATE INDEX IF NOT EXISTS "idx_${table.name}_${col.name}" ON "${table.name}" ("${col.name}");\n`;
    }
    if (indexedCols.length > 0) output += '\n';
  }

  return output;
}

export function generateMSSQL(schema: SchemaModel): string {
  let output = `-- Microsoft SQL Server (T-SQL) DDL Generated by RelationalCanvas\n-- Date: ${new Date().toISOString()}\n\n`;

  for (const table of schema.tables) {
    output += `CREATE TABLE [dbo].[${table.name}] (\n`;

    const lines: string[] = [];
    const pkColumns: string[] = [];

    for (const col of table.columns) {
      let type = normalizeType(col.type, 'mssql');

      let line = `  [${col.name}] ${type}`;

      if (col.isPrimaryKey) {
        pkColumns.push(`[${col.name}]`);
      }

      if (!col.isNullable && !col.isPrimaryKey) {
        line += ` NOT NULL`;
      }

      if (col.isUnique && !col.isPrimaryKey) {
        line += ` UNIQUE`;
      }

      if (col.defaultValue) {
        line += ` DEFAULT ${col.defaultValue}`;
      } else if (col.isPrimaryKey && type.toLowerCase().includes('uniqueidentifier')) {
        line += ` DEFAULT NEWID()`;
      }

      lines.push(line);
    }

    if (pkColumns.length > 0) {
      lines.push(`  CONSTRAINT [PK_${table.name}] PRIMARY KEY CLUSTERED (${pkColumns.join(', ')})`);
    }

    output += lines.join(',\n') + '\n);\nGO\n\n';

    // Explicit non-PK indexes
    const indexedCols = table.columns.filter(c => c.isIndexed && !c.isPrimaryKey && !c.isUnique);
    for (const col of indexedCols) {
      output += `CREATE NONCLUSTERED INDEX [IX_${table.name}_${col.name}] ON [dbo].[${table.name}] ([${col.name}]);\nGO\n\n`;
    }
  }

  // Generate foreign key constraints separately for T-SQL best practice
  if (schema.relationships.length > 0) {
    output += `-- Foreign Key Constraints\n`;
    for (const rel of schema.relationships) {
      const srcTable = schema.tables.find(t => t.id === rel.sourceTableId);
      const srcCol = srcTable?.columns.find(c => c.id === rel.sourceColumnId);
      const tgtTable = schema.tables.find(t => t.id === rel.targetTableId);
      const tgtCol = tgtTable?.columns.find(c => c.id === rel.targetColumnId);

      if (srcTable && srcCol && tgtTable && tgtCol) {
        output += `ALTER TABLE [dbo].[${srcTable.name}]\n`;
        output += `  ADD CONSTRAINT [FK_${srcTable.name}_${srcCol.name}]\n`;
        output += `  FOREIGN KEY ([${srcCol.name}]) REFERENCES [dbo].[${tgtTable.name}] ([${tgtCol.name}])`;
        if (rel.onDelete) {
          output += ` ON DELETE ${rel.onDelete}`;
        }
        output += `;\nGO\n\n`;
      }
    }
  }

  return output;
}

export function generateMySQL(schema: SchemaModel): string {
  let output = `-- MySQL DDL Generated by RelationalCanvas\n-- Date: ${new Date().toISOString()}\n\n`;

  for (const table of schema.tables) {
    output += `CREATE TABLE IF NOT EXISTS \`${table.name}\` (\n`;

    const lines: string[] = [];
    const pkColumns: string[] = [];

    for (const col of table.columns) {
      const type = normalizeType(col.type, 'mysql');
      let line = `  \`${col.name}\` ${type}`;

      if (col.isPrimaryKey) {
        pkColumns.push(`\`${col.name}\``);
      }

      if (!col.isNullable && !col.isPrimaryKey) {
        line += ` NOT NULL`;
      }

      if (col.isUnique && !col.isPrimaryKey) {
        line += ` UNIQUE`;
      }

      if (col.defaultValue) {
        line += ` DEFAULT ${col.defaultValue}`;
      }

      lines.push(line);
    }

    if (pkColumns.length > 0) {
      lines.push(`  PRIMARY KEY (${pkColumns.join(', ')})`);
    }

    const tableRels = schema.relationships.filter(r => r.sourceTableId === table.id);
    for (const rel of tableRels) {
      const srcCol = table.columns.find(c => c.id === rel.sourceColumnId);
      const tgtTable = schema.tables.find(t => t.id === rel.targetTableId);
      const tgtCol = tgtTable?.columns.find(c => c.id === rel.targetColumnId);

      if (srcCol && tgtTable && tgtCol) {
        lines.push(`  CONSTRAINT \`fk_${table.name}_${srcCol.name}\` FOREIGN KEY (\`${srcCol.name}\`) REFERENCES \`${tgtTable.name}\` (\`${tgtCol.name}\`) ON DELETE ${rel.onDelete || 'NO ACTION'}`);
      }
    }

    output += lines.join(',\n') + '\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n\n';

    // Explicit non-PK indexes
    const indexedCols = table.columns.filter(c => c.isIndexed && !c.isPrimaryKey && !c.isUnique);
    for (const col of indexedCols) {
      output += `CREATE INDEX \`idx_${table.name}_${col.name}\` ON \`${table.name}\` (\`${col.name}\`);\n`;
    }
    if (indexedCols.length > 0) output += '\n';
  }

  return output;
}

export function generateSQLite(schema: SchemaModel): string {
  let output = `-- SQLite DDL Generated by RelationalCanvas\n-- Date: ${new Date().toISOString()}\n\n`;

  for (const table of schema.tables) {
    output += `CREATE TABLE IF NOT EXISTS "${table.name}" (\n`;

    const lines: string[] = [];
    const pkColumns: string[] = [];

    for (const col of table.columns) {
      const type = normalizeType(col.type, 'sqlite');
      let line = `  "${col.name}" ${type}`;

      if (col.isPrimaryKey) {
        if (table.columns.filter(c => c.isPrimaryKey).length === 1 && type.toUpperCase().includes('INTEGER')) {
          line += ` PRIMARY KEY AUTOINCREMENT`;
        } else {
          pkColumns.push(`"${col.name}"`);
        }
      } else {
        if (!col.isNullable) line += ` NOT NULL`;
        if (col.isUnique) line += ` UNIQUE`;
        if (col.defaultValue) line += ` DEFAULT ${col.defaultValue}`;
      }

      lines.push(line);
    }

    if (pkColumns.length > 0) {
      lines.push(`  PRIMARY KEY (${pkColumns.join(', ')})`);
    }

    const tableRels = schema.relationships.filter(r => r.sourceTableId === table.id);
    for (const rel of tableRels) {
      const srcCol = table.columns.find(c => c.id === rel.sourceColumnId);
      const tgtTable = schema.tables.find(t => t.id === rel.targetTableId);
      const tgtCol = tgtTable?.columns.find(c => c.id === rel.targetColumnId);

      if (srcCol && tgtTable && tgtCol) {
        lines.push(`  FOREIGN KEY ("${srcCol.name}") REFERENCES "${tgtTable.name}" ("${tgtCol.name}")`);
      }
    }

    output += lines.join(',\n') + '\n);\n\n';

    // Explicit non-PK indexes
    const indexedCols = table.columns.filter(c => c.isIndexed && !c.isPrimaryKey && !c.isUnique);
    for (const col of indexedCols) {
      output += `CREATE INDEX IF NOT EXISTS "idx_${table.name}_${col.name}" ON "${table.name}" ("${col.name}");\n`;
    }
    if (indexedCols.length > 0) output += '\n';
  }

  return output;
}

export function generateDBML(schema: SchemaModel): string {
  let output = `// DBML ERD Generated by RelationalCanvas\n// Date: ${new Date().toISOString()}\n\n`;

  for (const table of schema.tables) {
    output += `Table ${table.name} {\n`;

    for (const col of table.columns) {
      const settings: string[] = [];
      if (col.isPrimaryKey) settings.push('pk');
      if (col.isUnique && !col.isPrimaryKey) settings.push('unique');
      if (!col.isNullable && !col.isPrimaryKey) settings.push('not null');
      if (col.defaultValue) settings.push(`default: \`${col.defaultValue}\``);

      const settingsStr = settings.length > 0 ? ` [${settings.join(', ')}]` : '';
      output += `  ${col.name} ${col.type}${settingsStr}\n`;
    }

    output += `}\n\n`;
  }

  // Relations
  if (schema.relationships.length > 0) {
    output += `// Relationships\n`;
    for (const rel of schema.relationships) {
      const srcTable = schema.tables.find(t => t.id === rel.sourceTableId);
      const srcCol = srcTable?.columns.find(c => c.id === rel.sourceColumnId);
      const tgtTable = schema.tables.find(t => t.id === rel.targetTableId);
      const tgtCol = tgtTable?.columns.find(c => c.id === rel.targetColumnId);

      if (srcTable && srcCol && tgtTable && tgtCol) {
        let symbol = '>';
        if (rel.cardinality === '1:1') symbol = '-';
        else if (rel.cardinality === 'N:M') symbol = '<>';
        else if (rel.cardinality === 'N:1') symbol = '<';

        output += `Ref: ${srcTable.name}.${srcCol.name} ${symbol} ${tgtTable.name}.${tgtCol.name}\n`;
      }
    }
  }

  return output;
}

export function generateMermaid(schema: SchemaModel): string {
  let output = `erDiagram\n`;

  // Write relationships first in Mermaid standard syntax
  for (const rel of schema.relationships) {
    const srcTable = schema.tables.find(t => t.id === rel.sourceTableId);
    const tgtTable = schema.tables.find(t => t.id === rel.targetTableId);

    if (srcTable && tgtTable) {
      let marker = '||--o{';
      if (rel.cardinality === '1:1') marker = '||--||';
      else if (rel.cardinality === 'N:M') marker = '}o--o{';
      else if (rel.cardinality === 'N:1') marker = '}o--||';

      output += `    ${tgtTable.name} ${marker} ${srcTable.name} : "references"\n`;
    }
  }

  output += '\n';

  for (const table of schema.tables) {
    output += `    ${table.name} {\n`;
    for (const col of table.columns) {
      let constraint = '';
      if (col.isPrimaryKey) constraint = ' PK';
      else if (col.isForeignKey) constraint = ' FK';
      else if (col.isUnique) constraint = ' UK';

      const sanitizedType = col.type.replace(/\s+/g, '_').replace(/[(),]/g, '');
      output += `        ${sanitizedType} ${col.name}${constraint}\n`;
    }
    output += `    }\n`;
  }

  return output;
}
