import { SchemaModel } from '../types/schema';

export const SAMPLE_SCHEMAS: Record<string, { name: string; description: string; schema: SchemaModel }> = {
  ecommerce: {
    name: 'E-Commerce & Orders',
    description: 'Relational shop architecture with users, orders, line items, products, and categories.',
    schema: {
      id: 'schema_ecommerce',
      name: 'E-Commerce Storefront',
      dialect: 'postgres',
      createdAt: Date.now(),
      updatedAt: Date.now(),
      tables: [
        {
          id: 'tbl_users',
          name: 'users',
          position: { x: 50, y: 60 },
          colorHeader: '#3B82F6',
          columns: [
            { id: 'u_id', name: 'id', type: 'uuid', isPrimaryKey: true, isForeignKey: false, isNullable: false, isUnique: true, defaultValue: 'gen_random_uuid()' },
            { id: 'u_email', name: 'email', type: 'varchar(255)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: true },
            { id: 'u_name', name: 'full_name', type: 'varchar(120)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false },
            { id: 'u_created', name: 'created_at', type: 'timestamptz', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false, defaultValue: 'NOW()' },
          ],
        },
        {
          id: 'tbl_orders',
          name: 'orders',
          position: { x: 440, y: 60 },
          colorHeader: '#10B981',
          columns: [
            { id: 'o_id', name: 'id', type: 'uuid', isPrimaryKey: true, isForeignKey: false, isNullable: false, isUnique: true, defaultValue: 'gen_random_uuid()' },
            { id: 'o_user_id', name: 'user_id', type: 'uuid', isPrimaryKey: false, isForeignKey: true, isNullable: false, isUnique: false, references: { targetTableId: 'tbl_users', targetColumnId: 'u_id', targetTableName: 'users', targetColumnName: 'id' } },
            { id: 'o_status', name: 'status', type: 'varchar(50)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false, defaultValue: "'pending'" },
            { id: 'o_total', name: 'total_amount', type: 'numeric(12,2)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false },
            { id: 'o_created', name: 'ordered_at', type: 'timestamptz', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false, defaultValue: 'NOW()' },
          ],
        },
        {
          id: 'tbl_order_items',
          name: 'order_items',
          position: { x: 840, y: 60 },
          colorHeader: '#10B981',
          columns: [
            { id: 'oi_id', name: 'id', type: 'uuid', isPrimaryKey: true, isForeignKey: false, isNullable: false, isUnique: true, defaultValue: 'gen_random_uuid()' },
            { id: 'oi_order_id', name: 'order_id', type: 'uuid', isPrimaryKey: false, isForeignKey: true, isNullable: false, isUnique: false, references: { targetTableId: 'tbl_orders', targetColumnId: 'o_id', targetTableName: 'orders', targetColumnName: 'id' } },
            { id: 'oi_product_id', name: 'product_id', type: 'uuid', isPrimaryKey: false, isForeignKey: true, isNullable: false, isUnique: false, references: { targetTableId: 'tbl_products', targetColumnId: 'p_id', targetTableName: 'products', targetColumnName: 'id' } },
            { id: 'oi_qty', name: 'quantity', type: 'integer', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false, defaultValue: '1' },
            { id: 'oi_price', name: 'unit_price', type: 'numeric(10,2)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false },
          ],
        },
        {
          id: 'tbl_products',
          name: 'products',
          position: { x: 840, y: 440 },
          colorHeader: '#8B5CF6',
          columns: [
            { id: 'p_id', name: 'id', type: 'uuid', isPrimaryKey: true, isForeignKey: false, isNullable: false, isUnique: true, defaultValue: 'gen_random_uuid()' },
            { id: 'p_category_id', name: 'category_id', type: 'uuid', isPrimaryKey: false, isForeignKey: true, isNullable: true, isUnique: false, references: { targetTableId: 'tbl_categories', targetColumnId: 'c_id', targetTableName: 'categories', targetColumnName: 'id' } },
            { id: 'p_sku', name: 'sku', type: 'varchar(64)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: true },
            { id: 'p_title', name: 'title', type: 'varchar(255)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false },
            { id: 'p_price', name: 'price', type: 'numeric(10,2)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false },
            { id: 'p_stock', name: 'stock_count', type: 'integer', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false, defaultValue: '0' },
          ],
        },
        {
          id: 'tbl_categories',
          name: 'categories',
          position: { x: 440, y: 440 },
          colorHeader: '#8B5CF6',
          columns: [
            { id: 'c_id', name: 'id', type: 'uuid', isPrimaryKey: true, isForeignKey: false, isNullable: false, isUnique: true, defaultValue: 'gen_random_uuid()' },
            { id: 'c_name', name: 'name', type: 'varchar(100)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: true },
            { id: 'c_slug', name: 'slug', type: 'varchar(120)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: true },
          ],
        },
        {
          id: 'tbl_reviews',
          name: 'reviews',
          position: { x: 50, y: 440 },
          colorHeader: '#F59E0B',
          columns: [
            { id: 'r_id', name: 'id', type: 'uuid', isPrimaryKey: true, isForeignKey: false, isNullable: false, isUnique: true, defaultValue: 'gen_random_uuid()' },
            { id: 'r_user_id', name: 'user_id', type: 'uuid', isPrimaryKey: false, isForeignKey: true, isNullable: false, isUnique: false, references: { targetTableId: 'tbl_users', targetColumnId: 'u_id', targetTableName: 'users', targetColumnName: 'id' } },
            { id: 'r_product_id', name: 'product_id', type: 'uuid', isPrimaryKey: false, isForeignKey: true, isNullable: false, isUnique: false, references: { targetTableId: 'tbl_products', targetColumnId: 'p_id', targetTableName: 'products', targetColumnName: 'id' } },
            { id: 'r_rating', name: 'rating', type: 'smallint', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false },
            { id: 'r_comment', name: 'comment', type: 'text', isPrimaryKey: false, isForeignKey: false, isNullable: true, isUnique: false },
          ],
        },
      ],
      relationships: [
        { id: 'rel_1', sourceTableId: 'tbl_orders', sourceColumnId: 'o_user_id', targetTableId: 'tbl_users', targetColumnId: 'u_id', cardinality: '1:N', name: 'user_orders' },
        { id: 'rel_2', sourceTableId: 'tbl_order_items', sourceColumnId: 'oi_order_id', targetTableId: 'tbl_orders', targetColumnId: 'o_id', cardinality: '1:N', name: 'order_line_items' },
        { id: 'rel_3', sourceTableId: 'tbl_order_items', sourceColumnId: 'oi_product_id', targetTableId: 'tbl_products', targetColumnId: 'p_id', cardinality: '1:N', name: 'product_order_items' },
        { id: 'rel_4', sourceTableId: 'tbl_products', sourceColumnId: 'p_category_id', targetTableId: 'tbl_categories', targetColumnId: 'c_id', cardinality: '1:N', name: 'category_products' },
        { id: 'rel_5', sourceTableId: 'tbl_reviews', sourceColumnId: 'r_user_id', targetTableId: 'tbl_users', targetColumnId: 'u_id', cardinality: '1:N', name: 'user_reviews' },
        { id: 'rel_6', sourceTableId: 'tbl_reviews', sourceColumnId: 'r_product_id', targetTableId: 'tbl_products', targetColumnId: 'p_id', cardinality: '1:N', name: 'product_reviews' },
      ],
    },
  },
  saas: {
    name: 'SaaS Multi-Tenant & Billing',
    description: 'Organizations, users, memberships, roles, subscription plans, and audit logging.',
    schema: {
      id: 'schema_saas',
      name: 'SaaS Multi-Tenant Architecture',
      dialect: 'mssql',
      createdAt: Date.now(),
      updatedAt: Date.now(),
      tables: [
        {
          id: 'tbl_orgs',
          name: 'Organizations',
          position: { x: 50, y: 60 },
          colorHeader: '#3B82F6',
          columns: [
            { id: 'org_id', name: 'Id', type: 'uniqueidentifier', isPrimaryKey: true, isForeignKey: false, isNullable: false, isUnique: true, defaultValue: 'NEWID()' },
            { id: 'org_name', name: 'Name', type: 'nvarchar(150)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false },
            { id: 'org_slug', name: 'Slug', type: 'nvarchar(80)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: true },
            { id: 'org_created', name: 'CreatedAt', type: 'datetime2', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false, defaultValue: 'SYSUTCDATETIME()' },
          ],
        },
        {
          id: 'tbl_members',
          name: 'OrganizationMembers',
          position: { x: 440, y: 60 },
          colorHeader: '#10B981',
          columns: [
            { id: 'mem_id', name: 'Id', type: 'uniqueidentifier', isPrimaryKey: true, isForeignKey: false, isNullable: false, isUnique: true, defaultValue: 'NEWID()' },
            { id: 'mem_org_id', name: 'OrganizationId', type: 'uniqueidentifier', isPrimaryKey: false, isForeignKey: true, isNullable: false, isUnique: false, references: { targetTableId: 'tbl_orgs', targetColumnId: 'org_id' } },
            { id: 'mem_user_id', name: 'UserId', type: 'uniqueidentifier', isPrimaryKey: false, isForeignKey: true, isNullable: false, isUnique: false, references: { targetTableId: 'tbl_users_saas', targetColumnId: 'u_saas_id' } },
            { id: 'mem_role', name: 'Role', type: 'nvarchar(50)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false, defaultValue: "'member'" },
          ],
        },
        {
          id: 'tbl_users_saas',
          name: 'Users',
          position: { x: 840, y: 60 },
          colorHeader: '#8B5CF6',
          columns: [
            { id: 'u_saas_id', name: 'Id', type: 'uniqueidentifier', isPrimaryKey: true, isForeignKey: false, isNullable: false, isUnique: true, defaultValue: 'NEWID()' },
            { id: 'u_saas_email', name: 'Email', type: 'nvarchar(255)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: true },
            { id: 'u_saas_is_active', name: 'IsActive', type: 'bit', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false, defaultValue: '1' },
          ],
        },
        {
          id: 'tbl_subs',
          name: 'Subscriptions',
          position: { x: 50, y: 440 },
          colorHeader: '#06B6D4',
          columns: [
            { id: 'sub_id', name: 'Id', type: 'uniqueidentifier', isPrimaryKey: true, isForeignKey: false, isNullable: false, isUnique: true, defaultValue: 'NEWID()' },
            { id: 'sub_org_id', name: 'OrganizationId', type: 'uniqueidentifier', isPrimaryKey: false, isForeignKey: true, isNullable: false, isUnique: true, references: { targetTableId: 'tbl_orgs', targetColumnId: 'org_id' } },
            { id: 'sub_tier', name: 'PlanTier', type: 'nvarchar(50)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false },
            { id: 'sub_status', name: 'Status', type: 'nvarchar(30)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false },
            { id: 'sub_valid_until', name: 'ExpiresAt', type: 'datetime2', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false },
          ],
        },
        {
          id: 'tbl_audit',
          name: 'AuditLogs',
          position: { x: 440, y: 440 },
          colorHeader: '#F59E0B',
          columns: [
            { id: 'aud_id', name: 'Id', type: 'bigint', isPrimaryKey: true, isForeignKey: false, isNullable: false, isUnique: true },
            { id: 'aud_org_id', name: 'OrganizationId', type: 'uniqueidentifier', isPrimaryKey: false, isForeignKey: true, isNullable: false, isUnique: false, references: { targetTableId: 'tbl_orgs', targetColumnId: 'org_id' } },
            { id: 'aud_action', name: 'Action', type: 'nvarchar(100)', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false },
            { id: 'aud_metadata', name: 'Payload', type: 'nvarchar(max)', isPrimaryKey: false, isForeignKey: false, isNullable: true, isUnique: false },
            { id: 'aud_time', name: 'Timestamp', type: 'datetime2', isPrimaryKey: false, isForeignKey: false, isNullable: false, isUnique: false, defaultValue: 'SYSUTCDATETIME()' },
          ],
        },
      ],
      relationships: [
        { id: 'rel_s1', sourceTableId: 'tbl_members', sourceColumnId: 'mem_org_id', targetTableId: 'tbl_orgs', targetColumnId: 'org_id', cardinality: '1:N' },
        { id: 'rel_s2', sourceTableId: 'tbl_members', sourceColumnId: 'mem_user_id', targetTableId: 'tbl_users_saas', targetColumnId: 'u_saas_id', cardinality: '1:N' },
        { id: 'rel_s3', sourceTableId: 'tbl_subs', sourceColumnId: 'sub_org_id', targetTableId: 'tbl_orgs', targetColumnId: 'org_id', cardinality: '1:1' },
        { id: 'rel_s4', sourceTableId: 'tbl_audit', sourceColumnId: 'aud_org_id', targetTableId: 'tbl_orgs', targetColumnId: 'org_id', cardinality: '1:N' },
      ],
    },
  },
};
